module.exports = {
  KNOWLEDGE_GRAPH_ENABLE:
    process.env.NEXT_PUBLIC_KNOWLEDGE_GRAPH_ENABLE || false,
  KNOWLEDGE_GRAPH_REFRESH_MINUTES:
    process.env.KNOWLEDGE_GRAPH_REFRESH_MINUTES || 10,
  KNOWLEDGE_GRAPH_DEPTH: process.env.NEXT_PUBLIC_KNOWLEDGE_GRAPH_DEPTH || 2,
  KNOWLEDGE_GRAPH_STORE:
    process.env.KNOWLEDGE_GRAPH_STORE || 'notionnext-knowledge-graph'
}
